name: Check Pull Requests

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ppolitov/pull_requests_action
          path: actions/pulls

      - name: Node Modules
        shell: bash
        working-directory: actions/pulls
        run: |
          npm install
          ls -l

      - name: Check Pull Requests
        uses: ./actions/pulls
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          slack_token: ${{ secrets.SLACK_ACCESS_TOKEN }}
