name: Report

on: [status]
# check_run: types: [completed, created]

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        if: ${{ always() }}
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
