name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Modules
        shell: bash
        run: npm install

      - name: Tests
        shell: bash
        run: npm test
